name: learning_letters_easy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  video_player: ^2.8.2

dev_dependencies:

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/videos/en/
     - assets/videos/ar/
     - assets/screenshots/en/
     - assets/screenshots/ar/
